version: '3.8'

services:
  usrp:
    build: .
    image: srsran_4g
    container_name: srsran_4g
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - .:/home/workspace      # 挂载宿主机源码
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - UHD_IMAGES_DIR=/usr/share/uhd/images
      - X310_INTERFACE=enp4s0  # 根据实际网口修改
    working_dir: /home/workspace/build
    stdin_open: true
    tty: true
    network_mode: "host"
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
      - SYS_ADMIN